### ISSUE TITLE
Lista de problemas

### ISSUE THREAD

**Issue by AlanCosta7** [emanuelgsouza/debate3d-site#21]
- Quando envio o link de um tema ou compartilho o CARD ele abre o dashboard.
- Colocar no menu opção para criar TEMA.
- Upload da imagem de perfil.
- Quando faço o upload da imagem nunca vai de primeira, mesmo colocando a imagem na dimensão certa.
- Tirar a página "seja um assinante" por enquanto. 
- O comentário não está sendo computado no CARD
- O criador de CARD está com um fundo muito escuro, quase não dá pra perceber a diferença do Azul e Vermelho quando muda a dicotomia.
- Em "Desenvolvido por EmanuelGDev e mantido por Alan Costa" o link do meu perfil está errado.

**Comment by emanuelgsouza** [comment]
Solução para o caso para a proteção das rotas: criar um mixin que insere a lógica de proteção da rota e caso seja necessário usá-lo

**Comment by AlanCosta7** [comment]
- Direcionar a entrada da landpage para o app na tela de TEMAS.
- Criar um popup de login para quando o usuário tentar interagir votando na enquete, interagindo ou criando CARD.

**Comment by emanuelgsouza** [comment]
Para a questão de bloquear o usuário quando interagir com a página, e interessante colocar um mixin com essa lógica e os componentes que forem ter ela, usarem o mixin.

A lógica desse problema foi colocada numa [nova issue](https://github.com/debate3d/debate3d-site/issues/22)
